include: ["_pages"]
permalink: /:year/:month/:day/:title/
title: Cipher 
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" 
url: "http://cipher.org.uk" 
github_username:  cphr

markdown: kramdown



